apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  containers:
  - env:
    - name: DATABASE_URL
      value: mysql+pymysql://web:PASSWORD@IP:3306/web
    - name: MAIL_PORT
      value: "1025"
    - name: MAIL_SERVER
      value: mailhog
    - name: MYSQL_ROOT_PASSWORD
      value: DHt3WVsPC8722dBQ
    - name: SECRET_KEY
      value: my-secret-key
    image: martin605/web
    name: web
    ports:
    - containerPort: 5000
    resources: {}
  restartPolicy: OnFailure
status: {}
